# -*- coding: utf-8 -*-
"""pred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yjygsCMdcHfw_KhlhlAill0A9gV7SYft
"""

import numpy as np
import pandas as pd
import re
import random
import math

def softmax(x):
  """
  Apply the softmax activation function to a numpy matrix 'x' of any shape.
  """
  exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
  return exp_x / exp_x.sum(axis=-1, keepdims=True)

def pred(w, X):
    """
    Compute the prediction made by a logistic regression model with weights `w`
    on the data set with input data matrix `X`.

    Parameters:
        `w` - a numpy array of shape (D+1, C)
        `X` - data matrix of shape (N, D+1)

    Returns: Prediction vector `y` of shape (N, C).
    """
    return softmax(np.dot(X, w))

def accuracy(w, X, t):
  """
  Compute the accuracy of a logistic regression model with weights `w`
  on the data set with input data matrix `X` and targets `t`

  Parameters:
        `w` - a numpy array of shape (D+1, C)
        `X` - data matrix of shape (N, D+1)
        `t` - target matrix of shape (N, C) (one-hot encoded)
  Returns: accuracy value, between 0 and 1.
  """
  y = pred(w, X)
  y_pred = np.argmax(y, axis=1)  # Predicted target
  t_true = np.argmax(t, axis=1)  # Real target
  return np.mean(y_pred == t_true)

def grad(w, X, t, lam=0.0):
    '''
    Return the gradient of the cost function at `w`. The cost function
    is the average cross-entropy loss across the data set `X` and the
    target vector `t`.

    Parameters:
        `w` - a current "guess" of what our weights should be,
                   a numpy array of shape (D+1, C)
        `X` - matrix of shape (N,D+1) of input features
        `t` - target y values of shape (N, C) (one-hot encoded)

    Returns: gradient matrix of shape (D+1, C)
    '''
    y = pred(w, X)
    N = X.shape[0]
    return (1 / N) * np.dot(X.T, (y - t)) + lam * w

def gradient_descent(X_set, t_set, epoch=5000, alpha=0.01, lam=0.0):
    weights = np.zeros((X_set.shape[1], t_set.shape[1]))

    for epo in range(epoch):
        gradient = grad(weights, X_set, t_set, lam=lam)
        weights = weights - alpha * gradient

    return weights

def predict_all(filename):
    data = pd.read_csv(filename)
    clean_data = data.copy()

    # Drop unused columns
    price = 'How much (in Canadian dollars) would you be willing to pay for this painting?'
    typed_answers = ["Describe how this painting makes you feel.", "If this painting was a food, what would be?",
                     "Imagine a soundtrack for this painting. Describe that soundtrack without naming any objects in the painting."]
    clean_data = clean_data.drop(columns=[price, *typed_answers, "unique_id"], errors='ignore')

    # Drop missing rows
    clean_data = clean_data.dropna()

    # One-hot encode sentiment columns
    discrete_columns = ["This art piece makes me feel sombre.", "This art piece makes me feel content.",
                        "This art piece makes me feel calm.", "This art piece makes me feel uneasy.", "Painting"]
    clean_data = pd.get_dummies(clean_data, columns=discrete_columns, dtype=int)

    # Encode room, person, season
    cleaned_room   = clean_data["If you could purchase this painting, which room would you put that painting in?"].str.get_dummies(sep=",")
    cleaned_person = clean_data["If you could view this art in person, who would you want to view it with?"].str.get_dummies(sep=",")
    cleaned_season = clean_data["What season does this art piece remind you of?"].str.get_dummies(sep=",")
    clean_data = clean_data.drop(columns=["If you could purchase this painting, which room would you put that painting in?",
                                          "If you could view this art in person, who would you want to view it with?",
                                          "What season does this art piece remind you of?"])
    clean_data = pd.concat([clean_data, cleaned_room, cleaned_person, cleaned_season], axis=1)

    # Gain target
    target = clean_data.loc[:, ["Painting_The Persistence of Memory", "Painting_The Starry Night", "Painting_The Water Lily Pond"]]
    clean_data = clean_data.drop(columns=["Painting_The Persistence of Memory", "Painting_The Starry Night", "Painting_The Water Lily Pond"], errors='ignore')



    # Predict
    for ind, row in clean_data.iterrows():
      w = gradient_descent(X_set=clean_data, t_set=target)
      predict = []
      predict.append(pred(w, row))
    return predict
